#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Com.Google.Android.Exoplayer.Demo.Resource", IsApplication=true)]

namespace Com.Google.Android.Exoplayer.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int subtitle_minimum_font_size = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int audio_controls = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int controls_root = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int debug_text_view = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int player_state_view = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int retry_button = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int root = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int sample_list = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int shutter = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int subtitles = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int surface_view = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int text_controls = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int verbose_log_controls = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int video_controls = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int video_frame = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int player_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int sample_chooser_activity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int sample_chooser_inline_header = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int application_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int audio = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int drm_error_not_supported = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int drm_error_unknown = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int drm_error_unsupported_scheme = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int enable_background_audio = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int logging = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int logging_normal = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int logging_verbose = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int off = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int retry = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int text = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int video = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int DemoButton = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int PlayerTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int RootTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
