#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCross.ExoPlayer.Droid.Resource", IsApplication=false)]

namespace MvvmCross.ExoPlayer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public static int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public static int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int MvvmCrossTagId = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int MvxBindingTagUnique = 2130903041;
			
			// aapt resource value: 0x7f030007
			public static int progress = 2130903047;
			
			// aapt resource value: 0x7f030002
			public static int root = 2130903042;
			
			// aapt resource value: 0x7f030005
			public static int shutter = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int subtitles = 2130903046;
			
			// aapt resource value: 0x7f030004
			public static int surface_view = 2130903044;
			
			// aapt resource value: 0x7f030003
			public static int video_frame = 2130903043;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int activity_videoplayer = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public static int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public static int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public static int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public static int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public static int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
